baseurl = "https://cs-aware-next.github.io" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "CS-AWARE-NEXT"
theme = "hugo-universal-theme"
themesDir = "template"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/img/cs-aware.png"
    weight     = 2

[[menu.main]]
    name       = "Project"
    identifier = "section.project"
    url        = ""
    weight     = 1
    parent     = "menu.about"
    post       = 1

[[menu.main]]
    name       = "Overview"
    url        = "/project_overview/"
    weight     = 1
    parent     = "section.project"

[[menu.main]]
    name       = "Objectives"
    url        = "/project_objectives/"
    weight     = 2
    parent     = "section.project"

[[menu.main]]
    name       = "Impact"
    url        = "/project_impact/"
    weight     = 3
    parent     = "section.project"

[[menu.main]]
    name       = "Partners"
    identifier = "section.partners"
    url        = ""
    weight     = 2
    parent     = "menu.about"
    post       = 1

[[menu.main]]
    name       = "Consortium"
    url        = "/consortium/"
    weight     = 1
    parent     = "section.partners"

[[menu.main]]
    name       = "Publications"
    identifier = "section.publications"
    url        = ""
    weight     = 1
    parent     = "menu.about"
    post       = 2

[[menu.main]]
    name       = "Visibility, media presence and events"
    identifier = "section.visibility"
    url        = ""
    weight     = 2
    parent     = "menu.about"
    post       = 2

[[menu.main]]
    name       = "GitHub"
    url        = "https://github.com/CS-AWARE-NEXT"
    weight     = 1
    parent     = "section.visibility"

[[menu.main]]
    name       = "Twitter"
    url        = "https://twitter.com/cs_aware_next"
    weight     = 1
    parent     = "section.visibility"

[[menu.main]]
    name       = "Events"
    url        = "/events/"
    weight     = 1
    parent     = "section.visibility"    

[[menu.main]]
    name       = "Reports & Deliverables"
    url        = "/project_publications/"
    weight     = 1
    parent     = "section.publications"

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"
    weight     = 4

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 5

[params]
    viewMorePostLink = "/blog/"
    author = "CS-AWARE-NEXT"
    defaultKeywords = ["cs-aware-next", "European Union", "Horizon Europe"]
    mainSections = ["blog"]
    defaultDescription = "CS-AWARE-NEXT addresses cybersecurity and collaboration within local/regional networks, in concert with the multi-level European cybersecurity framework as defined by the European cybersecurity strategy."

    # Social media
    twitter_site = "cs_aware_next" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/logo.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p> This project has received funding from the European Union’s Horizon Europe research and innovation programme under grant agreement No 101069543. This communication reflects only the author’s view and the Commission is not responsible for any use that may be made of the information it contains.</p>"
    copyright = "© CS-AWARE-NEXT Consortium, 2022 - 2024, all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "CS-AWARE-NEXT"

    logo = "img/logo-transparent.png"
    logo_small = "img/logo-small.png"
    eu_logo = "img/partners/eu_flag.jpg"
    termsofservice = "/tos"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Prof. Juha Röning</strong>
        <br><a href="mailto:&#074;&#117;&#104;&#097;&#046;&#082;&#111;&#110;&#105;&#110;&#103;&#064;&#111;&#117;&#108;&#117;&#046;&#102;&#105;" target="_blank" rel="noopener"><i class="fa fa-envelope" aria-hidden="true"></i></a> 
            <a href="tel:&#43;&#51;&#53;&#56;&#52;&#48;&#53;&#49;&#56;&#49;&#54;&#50;&#49;" target="_blank" rel="noopener"><i class="fa fa-phone" aria-hidden="true"></i></a> 
            <a href="https://www.oulu.fi/yliopisto/tutkija/juha-roning" target="_blank" rel="noopener"><i class="fa fa-link" aria-hidden="true"></i></a>
        <br>University of Oulu
        <br>Biomimetics and Intelligent Systems Group (BISG)
        <br>Pentti Kaiteran Katu 1
        <br>P.O. Box 4500
        <br>90014 OULU
        <br>Finland
        <br>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = true
    slide_speed = 100
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.objectives]
    enable = true
    cols = 2 # Default: 3, Available values 2,3,4,6
    title = "Objectives"
    # All objectives are defined in their own files. You can find example items
    # at 'exampleSite/data/objectives'.
    # For more information take a look at the README.

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Find out more"
    subtitle = "Learn more about the project's results in our deliverables."
    link_url = "/project_publications/"
    link_text = "Publications"

[params.partners]
    enable = true
    # All partners are defined in their own files. You can find example items
    # at 'exampleSite/data/partners'.
    # For more information take a look at the README.
    title = "Project Partners"
    subtitle = ""
    cols = 2 # default 3

[params.associatedpartners]
    enable = true
    title = "Associated Partners"
    subtitle = ""
    cols = 2 # default 3

[params.recent_posts]
    enable = true
    title = "Recent posts"
    subtitle = "You can follow the progress of the project by reading our blog posts."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
